name: publish-github-package

on:
  push:
    branches: [ 'master' ]

jobs:
  build-and-publish:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Gradle
        run: gradle sdk:assembleRelease

        # Runs upload, and then closes & releases the repository
      - name: Publish to MavenCentral
        run: gradle sdk:publishAllPublicationsToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}